#https://travis-ci.org/juanpablocamejo/sqrum
sudo: required
language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo cat Aptfile | sudo xargs apt-get install -y --force-yes
  - sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg --force-all -i google-chrome-stable_current_amd64.deb
install: "pip install -r requirements.txt"
script: xvfb-run nosetests -v pruebas/tests/*.py
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key: d75c7509-1a26-4283-ba25-3e59df710b8f
  app: sqrum
