#https://travis-ci.org/juanpablocamejo/sqrum
language: python
python:
  - "2.7"
# command to install dependencies
addons:
  apt:
    packages:
    - firefox
    - xvfb
install: "pip install -r requirements.txt"
script: xvfb-run nosetests pruebas/tests/*.py
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key: d75c7509-1a26-4283-ba25-3e59df710b8f
  app: sqrum