#https://travis-ci.org/juanpablocamejo/sqrum
sudo: required
language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - sudo cat Aptfile | xargs apt-get install
install: "pip install -r requirements.txt"
script: xvfb-run nosetests -v pruebas/tests/*.py
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key: d75c7509-1a26-4283-ba25-3e59df710b8f
  app: sqrum
