#https://travis-ci.org/juanpablocamejo/sqrum
sudo: required
language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i --no-force-depends google-chrome-stable_current_amd64.deb
  - apt-get -f install 
  - sudo cat Aptfile | xargs apt-get install
install: "pip install -r requirements.txt"
script: xvfb-run nosetests -v pruebas/tests/*.py
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key: d75c7509-1a26-4283-ba25-3e59df710b8f
  app: sqrum
